volumes:
  data:
    name: data
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  monosi-server:
    image: monosi/monosi-server:latest
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.api
    ports: 
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=server/wsgi.py
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_SCHEMA=public
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  monosi-client:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.client
    image: monosi/monosi-client:latest
    depends_on:
      - monosi-server
    environment:
      - REACT_APP_API_URL=/v1/api/
    ports:
      - "3000:80"
